/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aopus_OpusLibrary */

#ifndef _Included_aopus_OpusLibrary
#define _Included_aopus_OpusLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aopus_OpusLibrary
 * Method:    encoderCreate
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_aopus_OpusLibrary_encoderCreate
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     aopus_OpusLibrary
 * Method:    encoderDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_aopus_OpusLibrary_encoderDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     aopus_OpusLibrary
 * Method:    encoderEncode
 * Signature: (J[BII)I
 */
JNIEXPORT jbyteArray JNICALL Java_aopus_OpusLibrary_encoderEncode
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     aopus_OpusLibrary
 * Method:    decoderCreate
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_aopus_OpusLibrary_decoderCreate
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     aopus_OpusLibrary
 * Method:    decoderDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_aopus_OpusLibrary_decoderDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     aopus_OpusLibrary
 * Method:    decoderDecode
 * Signature: (J[B)I
 */
JNIEXPORT jbyteArray JNICALL Java_aopus_OpusLibrary_decoderDecode
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
