package vpx;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
import vpx.VpxLibrary.vpx_codec_err_t;
import vpx.VpxLibrary.vpx_codec_iface;
import vpx.VpxLibrary.vpx_codec_priv;
/**
 * <i>native declaration : vpx\vpx_codec.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vpx") 
public class vpx_codec_ctx_t extends StructObject {
	public vpx_codec_ctx_t() {
		super();
	}
	/**
	 * < Printable interface name<br>
	 * C type : const char*
	 */
	@Field(0) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * < Printable interface name<br>
	 * C type : const char*
	 */
	@Field(0) 
	public vpx_codec_ctx_t name(Pointer<Byte > name) {
		this.io.setPointerField(this, 0, name);
		return this;
	}
	/**
	 * < Interface pointers<br>
	 * C type : vpx_codec_iface_t*
	 */
	@Field(1) 
	public Pointer<vpx_codec_iface > iface() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * < Interface pointers<br>
	 * C type : vpx_codec_iface_t*
	 */
	@Field(1) 
	public vpx_codec_ctx_t iface(Pointer<vpx_codec_iface > iface) {
		this.io.setPointerField(this, 1, iface);
		return this;
	}
	/**
	 * < Last returned error<br>
	 * C type : vpx_codec_err_t
	 */
	@Field(2) 
	public IntValuedEnum<vpx_codec_err_t > err() {
		return this.io.getEnumField(this, 2);
	}
	/**
	 * < Last returned error<br>
	 * C type : vpx_codec_err_t
	 */
	@Field(2) 
	public vpx_codec_ctx_t err(IntValuedEnum<vpx_codec_err_t > err) {
		this.io.setEnumField(this, 2, err);
		return this;
	}
	/**
	 * < Detailed info, if available<br>
	 * C type : const char*
	 */
	@Field(3) 
	public Pointer<Byte > err_detail() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * < Detailed info, if available<br>
	 * C type : const char*
	 */
	@Field(3) 
	public vpx_codec_ctx_t err_detail(Pointer<Byte > err_detail) {
		this.io.setPointerField(this, 3, err_detail);
		return this;
	}
	/**
	 * < Flags passed at init time<br>
	 * C type : vpx_codec_flags_t
	 */
	@CLong 
	@Field(4) 
	public long init_flags() {
		return this.io.getCLongField(this, 4);
	}
	/**
	 * < Flags passed at init time<br>
	 * C type : vpx_codec_flags_t
	 */
	@CLong 
	@Field(4) 
	public vpx_codec_ctx_t init_flags(long init_flags) {
		this.io.setCLongField(this, 4, init_flags);
		return this;
	}
	/// C type : config_union
	@Field(5) 
	public vpx_codec_ctx_t.config_union config() {
		return this.io.getNativeObjectField(this, 5);
	}
	/// C type : config_union
	@Field(5) 
	public vpx_codec_ctx_t config(vpx_codec_ctx_t.config_union config) {
		this.io.setNativeObjectField(this, 5, config);
		return this;
	}
	/**
	 * < Algorithm private storage<br>
	 * C type : vpx_codec_priv_t*
	 */
	@Field(6) 
	public Pointer<vpx_codec_priv > priv() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * < Algorithm private storage<br>
	 * C type : vpx_codec_priv_t*
	 */
	@Field(6) 
	public vpx_codec_ctx_t priv(Pointer<vpx_codec_priv > priv) {
		this.io.setPointerField(this, 6, priv);
		return this;
	}
	/// <i>native declaration : vpx\vpx_codec.h:198</i>
	/// <i>native declaration : vpx\vpx_codec.h:198</i>
	@Union 
	public static class config_union extends StructObject {
		public config_union() {
			super();
		}
		/**
		 * < Decoder Configuration Pointer<br>
		 * C type : vpx_codec_dec_cfg*
		 */
		@Field(0) 
		public Pointer<vpx_codec_dec_cfg_t > dec() {
			return this.io.getPointerField(this, 0);
		}
		/**
		 * < Decoder Configuration Pointer<br>
		 * C type : vpx_codec_dec_cfg*
		 */
		@Field(0) 
		public config_union dec(Pointer<vpx_codec_dec_cfg_t > dec) {
			this.io.setPointerField(this, 0, dec);
			return this;
		}
		/**
		 * < Encoder Configuration Pointer<br>
		 * C type : vpx_codec_enc_cfg*
		 */
		@Field(1) 
		public Pointer<vpx_codec_enc_cfg_t > enc() {
			return this.io.getPointerField(this, 1);
		}
		/**
		 * < Encoder Configuration Pointer<br>
		 * C type : vpx_codec_enc_cfg*
		 */
		@Field(1) 
		public config_union enc(Pointer<vpx_codec_enc_cfg_t > enc) {
			this.io.setPointerField(this, 1, enc);
			return this;
		}
		/// C type : void*
		@Field(2) 
		public Pointer<? > raw() {
			return this.io.getPointerField(this, 2);
		}
		/// C type : void*
		@Field(2) 
		public config_union raw(Pointer<? > raw) {
			this.io.setPointerField(this, 2, raw);
			return this;
		}
		public config_union(Pointer pointer) {
			super(pointer);
		}
	};
	public vpx_codec_ctx_t(Pointer pointer) {
		super(pointer);
	}
}
