package vpx;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import vpx.VpxLibrary.vpx_ref_frame_type_t;
/**
 * <i>native declaration : vpx\vp8.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vpx") 
public class vpx_ref_frame_t extends StructObject {
	public vpx_ref_frame_t() {
		super();
	}
	/**
	 * < which reference frame<br>
	 * C type : vpx_ref_frame_type_t
	 */
	@Field(0) 
	public IntValuedEnum<vpx_ref_frame_type_t > frame_type() {
		return this.io.getEnumField(this, 0);
	}
	/**
	 * < which reference frame<br>
	 * C type : vpx_ref_frame_type_t
	 */
	@Field(0) 
	public vpx_ref_frame_t frame_type(IntValuedEnum<vpx_ref_frame_type_t > frame_type) {
		this.io.setEnumField(this, 0, frame_type);
		return this;
	}
	/**
	 * < reference frame data in image format<br>
	 * C type : vpx_image_t
	 */
	@Field(1) 
	public vpx_image_t img() {
		return this.io.getNativeObjectField(this, 1);
	}
	/**
	 * < reference frame data in image format<br>
	 * C type : vpx_image_t
	 */
	@Field(1) 
	public vpx_ref_frame_t img(vpx_image_t img) {
		this.io.setNativeObjectField(this, 1, img);
		return this;
	}
	public vpx_ref_frame_t(Pointer pointer) {
		super(pointer);
	}
}
