package vpx;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : vpx\vpx_encoder.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vpx") 
public class vpx_rational_t extends StructObject {
	public vpx_rational_t() {
		super();
	}
	/// < fraction numerator
	@Field(0) 
	public int num() {
		return this.io.getIntField(this, 0);
	}
	/// < fraction numerator
	@Field(0) 
	public vpx_rational_t num(int num) {
		this.io.setIntField(this, 0, num);
		return this;
	}
	/// < fraction denominator
	@Field(1) 
	public int den() {
		return this.io.getIntField(this, 1);
	}
	/// < fraction denominator
	@Field(1) 
	public vpx_rational_t den(int den) {
		this.io.setIntField(this, 1, den);
		return this;
	}
	public vpx_rational_t(Pointer pointer) {
		super(pointer);
	}
}
