package vpx;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : vpx\vpx_encoder.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vpx") 
public class vpx_fixed_buf_t extends StructObject {
	public vpx_fixed_buf_t() {
		super();
	}
	/**
	 * < Pointer to the data<br>
	 * C type : void*
	 */
	@Field(0) 
	public Pointer<? > buf() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * < Pointer to the data<br>
	 * C type : void*
	 */
	@Field(0) 
	public vpx_fixed_buf_t buf(Pointer<? > buf) {
		this.io.setPointerField(this, 0, buf);
		return this;
	}
	/// < Length of the buffer, in chars
	@Ptr 
	@Field(1) 
	public long sz() {
		return this.io.getSizeTField(this, 1);
	}
	/// < Length of the buffer, in chars
	@Ptr 
	@Field(1) 
	public vpx_fixed_buf_t sz(long sz) {
		this.io.setSizeTField(this, 1, sz);
		return this;
	}
	public vpx_fixed_buf_t(Pointer pointer) {
		super(pointer);
	}
}
