package vpx;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : vpx\vpx_image.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vpx") 
public class vpx_image_rect_t extends StructObject {
	public vpx_image_rect_t() {
		super();
	}
	/// < leftmost column
	@Field(0) 
	public int x() {
		return this.io.getIntField(this, 0);
	}
	/// < leftmost column
	@Field(0) 
	public vpx_image_rect_t x(int x) {
		this.io.setIntField(this, 0, x);
		return this;
	}
	/// < topmost row
	@Field(1) 
	public int y() {
		return this.io.getIntField(this, 1);
	}
	/// < topmost row
	@Field(1) 
	public vpx_image_rect_t y(int y) {
		this.io.setIntField(this, 1, y);
		return this;
	}
	/// < width
	@Field(2) 
	public int w() {
		return this.io.getIntField(this, 2);
	}
	/// < width
	@Field(2) 
	public vpx_image_rect_t w(int w) {
		this.io.setIntField(this, 2, w);
		return this;
	}
	/// < height
	@Field(3) 
	public int h() {
		return this.io.getIntField(this, 3);
	}
	/// < height
	@Field(3) 
	public vpx_image_rect_t h(int h) {
		this.io.setIntField(this, 3, h);
		return this;
	}
	public vpx_image_rect_t(Pointer pointer) {
		super(pointer);
	}
}
