package vpx;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : vpx\vpx_decoder.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vpx") 
public class vpx_codec_stream_info_t extends StructObject {
	public vpx_codec_stream_info_t() {
		super();
	}
	/// < Size of this structure
	@Field(0) 
	public int sz() {
		return this.io.getIntField(this, 0);
	}
	/// < Size of this structure
	@Field(0) 
	public vpx_codec_stream_info_t sz(int sz) {
		this.io.setIntField(this, 0, sz);
		return this;
	}
	/// < Width (or 0 for unknown/default)
	@Field(1) 
	public int w() {
		return this.io.getIntField(this, 1);
	}
	/// < Width (or 0 for unknown/default)
	@Field(1) 
	public vpx_codec_stream_info_t w(int w) {
		this.io.setIntField(this, 1, w);
		return this;
	}
	/// < Height (or 0 for unknown/default)
	@Field(2) 
	public int h() {
		return this.io.getIntField(this, 2);
	}
	/// < Height (or 0 for unknown/default)
	@Field(2) 
	public vpx_codec_stream_info_t h(int h) {
		this.io.setIntField(this, 2, h);
		return this;
	}
	/// < Current frame is a keyframe
	@Field(3) 
	public int is_kf() {
		return this.io.getIntField(this, 3);
	}
	/// < Current frame is a keyframe
	@Field(3) 
	public vpx_codec_stream_info_t is_kf(int is_kf) {
		this.io.setIntField(this, 3, is_kf);
		return this;
	}
	public vpx_codec_stream_info_t(Pointer pointer) {
		super(pointer);
	}
}
