package vpx;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : vpx\vp8cx.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vpx") 
public class vpx_roi_map_t extends StructObject {
	public vpx_roi_map_t() {
		super();
	}
	/**
	 * < specify an id between 0 and 3 for each 16x16 region within a frame<br>
	 * C type : unsigned char*
	 */
	@Field(0) 
	public Pointer<Byte > roi_map() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * < specify an id between 0 and 3 for each 16x16 region within a frame<br>
	 * C type : unsigned char*
	 */
	@Field(0) 
	public vpx_roi_map_t roi_map(Pointer<Byte > roi_map) {
		this.io.setPointerField(this, 0, roi_map);
		return this;
	}
	/// < number of rows
	@Field(1) 
	public int rows() {
		return this.io.getIntField(this, 1);
	}
	/// < number of rows
	@Field(1) 
	public vpx_roi_map_t rows(int rows) {
		this.io.setIntField(this, 1, rows);
		return this;
	}
	/// < number of cols
	@Field(2) 
	public int cols() {
		return this.io.getIntField(this, 2);
	}
	/// < number of cols
	@Field(2) 
	public vpx_roi_map_t cols(int cols) {
		this.io.setIntField(this, 2, cols);
		return this;
	}
	/**
	 * < quantizer delta [-63, 63] off baseline for regions with id between 0 and 3<br>
	 * C type : int[4]
	 */
	@Array({4}) 
	@Field(3) 
	public Pointer<Integer > delta_q() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * < loop filter strength delta [-63, 63] for regions with id between 0 and 3<br>
	 * C type : int[4]
	 */
	@Array({4}) 
	@Field(4) 
	public Pointer<Integer > delta_lf() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * < threshold for region to be treated as static<br>
	 * C type : unsigned int[4]
	 */
	@Array({4}) 
	@Field(5) 
	public Pointer<Integer > static_threshold() {
		return this.io.getPointerField(this, 5);
	}
	public vpx_roi_map_t(Pointer pointer) {
		super(pointer);
	}
}
