package vpx;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import vpx.VpxLibrary.vpx_img_fmt_t;
/**
 * <i>native declaration : vpx\vpx_image.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vpx") 
public class vpx_image_t extends StructObject {
	public vpx_image_t() {
		super();
	}
	/**
	 * < Image Format<br>
	 * C type : vpx_img_fmt_t
	 */
	@Field(0) 
	public IntValuedEnum<vpx_img_fmt_t > fmt() {
		return this.io.getEnumField(this, 0);
	}
	/**
	 * < Image Format<br>
	 * C type : vpx_img_fmt_t
	 */
	@Field(0) 
	public vpx_image_t fmt(IntValuedEnum<vpx_img_fmt_t > fmt) {
		this.io.setEnumField(this, 0, fmt);
		return this;
	}
	/**
	 * Image storage dimensions<br>
	 * < Stored image width
	 */
	@Field(1) 
	public int w() {
		return this.io.getIntField(this, 1);
	}
	/**
	 * Image storage dimensions<br>
	 * < Stored image width
	 */
	@Field(1) 
	public vpx_image_t w(int w) {
		this.io.setIntField(this, 1, w);
		return this;
	}
	/// < Stored image height
	@Field(2) 
	public int h() {
		return this.io.getIntField(this, 2);
	}
	/// < Stored image height
	@Field(2) 
	public vpx_image_t h(int h) {
		this.io.setIntField(this, 2, h);
		return this;
	}
	/**
	 * Image display dimensions<br>
	 * < Displayed image width
	 */
	@Field(3) 
	public int d_w() {
		return this.io.getIntField(this, 3);
	}
	/**
	 * Image display dimensions<br>
	 * < Displayed image width
	 */
	@Field(3) 
	public vpx_image_t d_w(int d_w) {
		this.io.setIntField(this, 3, d_w);
		return this;
	}
	/// < Displayed image height
	@Field(4) 
	public int d_h() {
		return this.io.getIntField(this, 4);
	}
	/// < Displayed image height
	@Field(4) 
	public vpx_image_t d_h(int d_h) {
		this.io.setIntField(this, 4, d_h);
		return this;
	}
	/**
	 * Chroma subsampling info<br>
	 * < subsampling order, X
	 */
	@Field(5) 
	public int x_chroma_shift() {
		return this.io.getIntField(this, 5);
	}
	/**
	 * Chroma subsampling info<br>
	 * < subsampling order, X
	 */
	@Field(5) 
	public vpx_image_t x_chroma_shift(int x_chroma_shift) {
		this.io.setIntField(this, 5, x_chroma_shift);
		return this;
	}
	/// < subsampling order, Y
	@Field(6) 
	public int y_chroma_shift() {
		return this.io.getIntField(this, 6);
	}
	/// < subsampling order, Y
	@Field(6) 
	public vpx_image_t y_chroma_shift(int y_chroma_shift) {
		this.io.setIntField(this, 6, y_chroma_shift);
		return this;
	}
	/**
	 * < pointer to the top left pixel for each plane<br>
	 * C type : unsigned char*[4]
	 */
	@Array({4}) 
	@Field(7) 
	public Pointer<Pointer<Byte > > planes() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * < stride between rows for each plane<br>
	 * C type : int[4]
	 */
	@Array({4}) 
	@Field(8) 
	public Pointer<Integer > stride() {
		return this.io.getPointerField(this, 8);
	}
	/// < bits per sample (for packed formats)
	@Field(9) 
	public int bps() {
		return this.io.getIntField(this, 9);
	}
	/// < bits per sample (for packed formats)
	@Field(9) 
	public vpx_image_t bps(int bps) {
		this.io.setIntField(this, 9, bps);
		return this;
	}
	/**
	 * The following member may be set by the application to associate data<br>
	 * with this image.<br>
	 * < may be set by the application to associate data<br>
	 *   with this image.<br>
	 * C type : void*
	 */
	@Field(10) 
	public Pointer<? > user_priv() {
		return this.io.getPointerField(this, 10);
	}
	/**
	 * The following member may be set by the application to associate data<br>
	 * with this image.<br>
	 * < may be set by the application to associate data<br>
	 *   with this image.<br>
	 * C type : void*
	 */
	@Field(10) 
	public vpx_image_t user_priv(Pointer<? > user_priv) {
		this.io.setPointerField(this, 10, user_priv);
		return this;
	}
	/**
	 * The following members should be treated as private.<br>
	 * < private<br>
	 * C type : unsigned char*
	 */
	@Field(11) 
	public Pointer<Byte > img_data() {
		return this.io.getPointerField(this, 11);
	}
	/**
	 * The following members should be treated as private.<br>
	 * < private<br>
	 * C type : unsigned char*
	 */
	@Field(11) 
	public vpx_image_t img_data(Pointer<Byte > img_data) {
		this.io.setPointerField(this, 11, img_data);
		return this;
	}
	/// < private
	@Field(12) 
	public int img_data_owner() {
		return this.io.getIntField(this, 12);
	}
	/// < private
	@Field(12) 
	public vpx_image_t img_data_owner(int img_data_owner) {
		this.io.setIntField(this, 12, img_data_owner);
		return this;
	}
	/// < private
	@Field(13) 
	public int self_allocd() {
		return this.io.getIntField(this, 13);
	}
	/// < private
	@Field(13) 
	public vpx_image_t self_allocd(int self_allocd) {
		this.io.setIntField(this, 13, self_allocd);
		return this;
	}
	public vpx_image_t(Pointer pointer) {
		super(pointer);
	}
}
