package vpx;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : vpx\vpx_codec.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vpx") 
public class vpx_codec_mmap_t extends StructObject {
	public vpx_codec_mmap_t() {
		super();
	}
	/**
	 * The following members are set by the codec when requesting a segment<br>
	 * < identifier for the segment's contents
	 */
	@Field(0) 
	public int id() {
		return this.io.getIntField(this, 0);
	}
	/**
	 * The following members are set by the codec when requesting a segment<br>
	 * < identifier for the segment's contents
	 */
	@Field(0) 
	public vpx_codec_mmap_t id(int id) {
		this.io.setIntField(this, 0, id);
		return this;
	}
	/// < size of the segment, in bytes
	@CLong 
	@Field(1) 
	public long sz() {
		return this.io.getCLongField(this, 1);
	}
	/// < size of the segment, in bytes
	@CLong 
	@Field(1) 
	public vpx_codec_mmap_t sz(long sz) {
		this.io.setCLongField(this, 1, sz);
		return this;
	}
	/// < required alignment of the segment, in bytes
	@Field(2) 
	public int align() {
		return this.io.getIntField(this, 2);
	}
	/// < required alignment of the segment, in bytes
	@Field(2) 
	public vpx_codec_mmap_t align(int align) {
		this.io.setIntField(this, 2, align);
		return this;
	}
	/// < bitfield containing segment properties
	@Field(3) 
	public int flags() {
		return this.io.getIntField(this, 3);
	}
	/// < bitfield containing segment properties
	@Field(3) 
	public vpx_codec_mmap_t flags(int flags) {
		this.io.setIntField(this, 3, flags);
		return this;
	}
	/**
	 * The following members are to be filled in by the allocation function<br>
	 * < pointer to the allocated segment<br>
	 * C type : void*
	 */
	@Field(4) 
	public Pointer<? > base() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * The following members are to be filled in by the allocation function<br>
	 * < pointer to the allocated segment<br>
	 * C type : void*
	 */
	@Field(4) 
	public vpx_codec_mmap_t base(Pointer<? > base) {
		this.io.setPointerField(this, 4, base);
		return this;
	}
	/**
	 * < destructor to call<br>
	 * C type : dtor_callback
	 */
	@Field(5) 
	public Pointer<vpx_codec_mmap_t.dtor_callback > dtor() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * < destructor to call<br>
	 * C type : dtor_callback
	 */
	@Field(5) 
	public vpx_codec_mmap_t dtor(Pointer<vpx_codec_mmap_t.dtor_callback > dtor) {
		this.io.setPointerField(this, 5, dtor);
		return this;
	}
	/**
	 * < allocator private storage<br>
	 * C type : void*
	 */
	@Field(6) 
	public Pointer<? > priv() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * < allocator private storage<br>
	 * C type : void*
	 */
	@Field(6) 
	public vpx_codec_mmap_t priv(Pointer<? > priv) {
		this.io.setPointerField(this, 6, priv);
		return this;
	}
	/// <i>native declaration : vpx\vpx_codec.h</i>
	/// <i>native declaration : vpx\vpx_codec.h</i>
	public static abstract class dtor_callback extends Callback<dtor_callback > {
		abstract public void apply(Pointer<vpx_codec_mmap_t > map);
	};
	public vpx_codec_mmap_t(Pointer pointer) {
		super(pointer);
	}
}
