package vpx;

import jvp8.VpxCodecCxPacketAlignmentFix;

import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.bridj.ann.Struct;
import org.bridj.ann.Union;
import vpx.VpxLibrary.vpx_codec_cx_pkt_kind;
/**
 * <i>native declaration : vpx\vpx_encoder.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vpx") 
@Struct(customizer = VpxCodecCxPacketAlignmentFix.class)
public class vpx_codec_cx_pkt_t extends StructObject {
	public vpx_codec_cx_pkt_t() {
		super();
	}
	/**
	 * < packet variant<br>
	 * C type : vpx_codec_cx_pkt_kind
	 */
	@Field(0) 
	public IntValuedEnum<vpx_codec_cx_pkt_kind > kind() {
		return this.io.getEnumField(this, 0);
	}
	/**
	 * < packet variant<br>
	 * C type : vpx_codec_cx_pkt_kind
	 */
	@Field(0) 
	public vpx_codec_cx_pkt_t kind(IntValuedEnum<vpx_codec_cx_pkt_kind > kind) {
		this.io.setEnumField(this, 0, kind);
		return this;
	}
	/// C type : data_union
	@Field(1) 
	public vpx_codec_cx_pkt_t.data_union data() {
		return this.io.getNativeObjectField(this, 1);
	}
	/// C type : data_union
	@Field(1) 
	public vpx_codec_cx_pkt_t data(vpx_codec_cx_pkt_t.data_union data) {
		this.io.setNativeObjectField(this, 1, data);
		return this;
	}
	/// <i>native declaration : vpx\vpx_encoder.h:154</i>
	/// <i>native declaration : vpx\vpx_encoder.h:154</i>
	@Union 
	public static class data_union extends StructObject {
		public data_union() {
			super();
		}
		/// C type : frame_struct
		@Field(0) 
		public vpx_codec_cx_pkt_t.data_union.frame_struct frame() {
			return this.io.getNativeObjectField(this, 0);
		}
		/// C type : frame_struct
		@Field(0) 
		public data_union frame(vpx_codec_cx_pkt_t.data_union.frame_struct frame) {
			this.io.setNativeObjectField(this, 0, frame);
			return this;
		}
		/**
		 * < data for two-pass packet<br>
		 * C type : vpx_fixed_buf
		 */
		@Field(1) 
		public vpx_fixed_buf_t twopass_stats() {
			return this.io.getNativeObjectField(this, 1);
		}
		/**
		 * < data for two-pass packet<br>
		 * C type : vpx_fixed_buf
		 */
		@Field(1) 
		public data_union twopass_stats(vpx_fixed_buf_t twopass_stats) {
			this.io.setNativeObjectField(this, 1, twopass_stats);
			return this;
		}
		/// C type : vpx_psnr_pkt
		@Field(2) 
		public vpx_codec_cx_pkt_t.data_union.vpx_psnr_pkt psnr() {
			return this.io.getNativeObjectField(this, 2);
		}
		/// C type : vpx_psnr_pkt
		@Field(2) 
		public data_union psnr(vpx_codec_cx_pkt_t.data_union.vpx_psnr_pkt psnr) {
			this.io.setNativeObjectField(this, 2, psnr);
			return this;
		}
		/**
		 * < data for arbitrary packets<br>
		 * C type : vpx_fixed_buf
		 */
		@Field(3) 
		public vpx_fixed_buf_t raw() {
			return this.io.getNativeObjectField(this, 3);
		}
		/**
		 * < data for arbitrary packets<br>
		 * C type : vpx_fixed_buf
		 */
		@Field(3) 
		public data_union raw(vpx_fixed_buf_t raw) {
			this.io.setNativeObjectField(this, 3, raw);
			return this;
		}
		/// Conversion Error : 128 - sizeof(vpx_codec_cx_pkt_kind)
		/// <i>native declaration : vpx\vpx_encoder.h:156</i>
		/// <i>native declaration : vpx\vpx_encoder.h:156</i>
		public static class frame_struct extends StructObject {
			public frame_struct() {
				super();
			}
			/**
			 * < compressed data buffer<br>
			 * C type : void*
			 */
			@Field(0) 
			public Pointer<? > buf() {
				return this.io.getPointerField(this, 0);
			}
			/**
			 * < compressed data buffer<br>
			 * C type : void*
			 */
			@Field(0) 
			public frame_struct buf(Pointer<? > buf) {
				this.io.setPointerField(this, 0, buf);
				return this;
			}
			/// < length of compressed data
			@Ptr 
			@Field(1) 
			public long sz() {
				return this.io.getSizeTField(this, 1);
			}
			/// < length of compressed data
			@Ptr 
			@Field(1) 
			public frame_struct sz(long sz) {
				this.io.setSizeTField(this, 1, sz);
				return this;
			}
			/**
			 * < time stamp to show frame<br>
			 * (in timebase units)<br>
			 * C type : vpx_codec_pts_t
			 */
			@Field(2) 
			public long pts() {
				return this.io.getLongField(this, 2);
			}
			/**
			 * < time stamp to show frame<br>
			 * (in timebase units)<br>
			 * C type : vpx_codec_pts_t
			 */
			@Field(2) 
			public frame_struct pts(long pts) {
				this.io.setLongField(this, 2, pts);
				return this;
			}
			/**
			 * < duration to show frame<br>
			 * (in timebase units)
			 */
			@CLong 
			@Field(3) 
			public long duration() {
				return this.io.getCLongField(this, 3);
			}
			/**
			 * < duration to show frame<br>
			 * (in timebase units)
			 */
			@CLong 
			@Field(3) 
			public frame_struct duration(long duration) {
				this.io.setCLongField(this, 3, duration);
				return this;
			}
			/**
			 * < flags for this frame<br>
			 * C type : vpx_codec_frame_flags_t
			 */
			@Field(4) 
			public int flags() {
				return this.io.getIntField(this, 4);
			}
			/**
			 * < flags for this frame<br>
			 * C type : vpx_codec_frame_flags_t
			 */
			@Field(4) 
			public frame_struct flags(int flags) {
				this.io.setIntField(this, 4, flags);
				return this;
			}
			/**
			 * < the partition id<br>
			 * defines the decoding order<br>
			 * of the partitions. Only<br>
			 * applicable when "output partition"<br>
			 * mode is enabled. First partition<br>
			 * has id 0.
			 */
			@Field(5) 
			public int partition_id() {
				return this.io.getIntField(this, 5);
			}
			/**
			 * < the partition id<br>
			 * defines the decoding order<br>
			 * of the partitions. Only<br>
			 * applicable when "output partition"<br>
			 * mode is enabled. First partition<br>
			 * has id 0.
			 */
			@Field(5) 
			public frame_struct partition_id(int partition_id) {
				this.io.setIntField(this, 5, partition_id);
				return this;
			}
			public frame_struct(Pointer pointer) {
				super(pointer);
			}
		};
		/// <i>native declaration : vpx\vpx_encoder.h:174</i>
		/// <i>native declaration : vpx\vpx_encoder.h:174</i>
		public static class vpx_psnr_pkt extends StructObject {
			public vpx_psnr_pkt() {
				super();
			}
			/**
			 * < Number of samples, total/y/u/v<br>
			 * C type : unsigned int[4]
			 */
			@Array({4}) 
			@Field(0) 
			public Pointer<Integer > samples() {
				return this.io.getPointerField(this, 0);
			}
			/**
			 * < sum squared error, total/y/u/v<br>
			 * C type : uint64_t[4]
			 */
			@Array({4}) 
			@Field(1) 
			public Pointer<Long > sse() {
				return this.io.getPointerField(this, 1);
			}
			/**
			 * < PSNR, total/y/u/v<br>
			 * C type : double[4]
			 */
			@Array({4}) 
			@Field(2) 
			public Pointer<Double > psnr() {
				return this.io.getPointerField(this, 2);
			}
			public vpx_psnr_pkt(Pointer pointer) {
				super(pointer);
			}
		};
		public data_union(Pointer pointer) {
			super(pointer);
		}
	};
	public vpx_codec_cx_pkt_t(Pointer pointer) {
		super(pointer);
	}
}
