package vpx;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import vpx.VpxLibrary.VPX_SCALING_MODE;
/**
 * <i>native declaration : vpx\vp8cx.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vpx") 
public class vpx_scaling_mode_t extends StructObject {
	public vpx_scaling_mode_t() {
		super();
	}
	/**
	 * < horizontal scaling mode<br>
	 * C type : VPX_SCALING_MODE
	 */
	@Field(0) 
	public IntValuedEnum<VPX_SCALING_MODE > h_scaling_mode() {
		return this.io.getEnumField(this, 0);
	}
	/**
	 * < horizontal scaling mode<br>
	 * C type : VPX_SCALING_MODE
	 */
	@Field(0) 
	public vpx_scaling_mode_t h_scaling_mode(IntValuedEnum<VPX_SCALING_MODE > h_scaling_mode) {
		this.io.setEnumField(this, 0, h_scaling_mode);
		return this;
	}
	/**
	 * < vertical scaling mode<br>
	 * C type : VPX_SCALING_MODE
	 */
	@Field(1) 
	public IntValuedEnum<VPX_SCALING_MODE > v_scaling_mode() {
		return this.io.getEnumField(this, 1);
	}
	/**
	 * < vertical scaling mode<br>
	 * C type : VPX_SCALING_MODE
	 */
	@Field(1) 
	public vpx_scaling_mode_t v_scaling_mode(IntValuedEnum<VPX_SCALING_MODE > v_scaling_mode) {
		this.io.setEnumField(this, 1, v_scaling_mode);
		return this;
	}
	public vpx_scaling_mode_t(Pointer pointer) {
		super(pointer);
	}
}
