package vpx;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : vpx\vpx_decoder.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vpx") 
public class vpx_codec_dec_cfg_t extends StructObject {
	public vpx_codec_dec_cfg_t() {
		super();
	}
	/// < Maximum number of threads to use, default 1
	@Field(0) 
	public int threads() {
		return this.io.getIntField(this, 0);
	}
	/// < Maximum number of threads to use, default 1
	@Field(0) 
	public vpx_codec_dec_cfg_t threads(int threads) {
		this.io.setIntField(this, 0, threads);
		return this;
	}
	/// < Width
	@Field(1) 
	public int w() {
		return this.io.getIntField(this, 1);
	}
	/// < Width
	@Field(1) 
	public vpx_codec_dec_cfg_t w(int w) {
		this.io.setIntField(this, 1, w);
		return this;
	}
	/// < Height
	@Field(2) 
	public int h() {
		return this.io.getIntField(this, 2);
	}
	/// < Height
	@Field(2) 
	public vpx_codec_dec_cfg_t h(int h) {
		this.io.setIntField(this, 2, h);
		return this;
	}
	public vpx_codec_dec_cfg_t(Pointer pointer) {
		super(pointer);
	}
}
